Controllers films users
Shelopuhina/java-filmorate pull request #4
Opened 2023-07-22 18:03 UTC by Shelopuhina

2023-07-23 09:31 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DataController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
Попытка как-то обобщить замечена, но не засчитана.
Нужно обобщить а не делать композицию
public class Controller<T extends Entity> {
	private final HashMap<Long, T> storage = new HashMap<>();
	private long counter = 0L;

       // общие методы по созданию, обновлению, получению
       // также можно добавить абстрактный метод по валидации
}

2023-07-23 09:34 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
У фильма и юзера есть общая часть, поле id. Можно сделать базовый класс Entity с полем id, от него занаследоваться и его же использовать в базовом контроллере.

2023-07-23 09:36 UTC, VadimZharkov requested changes
Нужно доработать.

2023-07-23 13:02 UTC, Shelopuhina commented
добавила абстрактный класс, объединила методы создания и обновления. Хранение всех сущностей теперьв одной мапе.

2023-07-24 07:00 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/DataController.java
> +        if (obj.getClass().equals(Film.class)) {
Вместо Object попробуй использовать дженерики. В базовом контроллере не должно быть никаких приведений к конкретным типам сущностей. Есть базовый контроллер и есть базовая сущность, их и нужно использовать вместе. А отличная от общей функциональность реализуется уже в наследниках, причем  родитель (базовый класс) не должен вообще ничего знать о деталях реализации у наследников.

2023-07-24 07:01 UTC, VadimZharkov requested changes
Нужно еще поработать.

2023-07-24 17:30 UTC, Shelopuhina commented
теперь базовый контроллер работает на дженериках. Код выглядит сильно проще..:)

2023-08-17 05:23 UTC, merged