Add friends likes
Shelopuhina/java-filmorate pull request #5
Opened 2023-08-16 09:46 UTC by Shelopuhina

2023-08-16 09:49 UTC, Shelopuhina commented
Добрый день! простите, что так затянула с заданием. 
Есть один момент, который не смогла преодолеть. Когда проходила тесты в постмане по предложенному json из тех задания, не проходил тест "GET Film most popular film". Хотя по дебагу смотрела - метод работает правильно.

2023-08-17 06:22 UTC, Shelopuhina commented
пробовала снова и снова, и нашла опечатку в методе лайков. теперь все тесты корректны.

2023-08-17 07:22 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Entity.java
> +    public abstract void isValidate(Object obj);
validate - глагол, is - тоже глагол,  требует прилагательного. поэтому
или validate  или isValid

2023-08-17 07:30 UTC, VadimZharkov requested changes
Есть что обобщить. У хранилищ одинаковая логика. Поэтому можно сделать

```
public interface Storage<T extends Entity> {
	void create(T data);

	void update(T data);

	T get(long id);

	void delete(long id);

	List<T> getAll();
}
```
Далее сделать его реализацию

public class InMemoryStorage<T extends Entity> implements Storage<T> {
	private final HashMap<Long, T> storage = new HashMap<>();
        // идентификатор
        // и реализация методов
}

оставшуюся логику типа лайков и добавления в друзья сделать уже не в классах хранилищ, а в классах сервисах

2023-08-20 16:47 UTC, Shelopuhina commented
еще раз спасибо за помощь,без вас я бы точно сошла с ума!:) 
теперь буду знать, что идея может вот так вот выкаблучиваться. помогло в итоге  “File” -> “Invalidate Caches"

2023-08-21 05:34 UTC, VadimZharkov approved these changes

2023-08-29 01:30 UTC, merged